image: themattrix/tox:latest

pipelines:
  default:
    - step:
        script:
          - pip install -U setuptools
          - pip install -U mercurial
          - pip --version
          - tox --version
          - tox
